### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by wenjdu**
Markdown language. For now, I didn't separate the plans and the title inside a "page", so it might be confusing. The separation will come later.

I have a main idea on how we will organize the documentation.

Inspiration comes from different doc, mainly Stripe, then; Factual, Pusher, PubNub.

This file is not the final one.

### CODE REVIEW

**Comment by wenjdu** [comment]
Don't mind the title and the plans. 

Let's focus on the content, please review 💯

**Review by elsener — APPROVED** [review]
Thanks jdu, I will now integrate this version to Jenkill "theme"

**Comment by maciejburda** [comment]
@wenjdu did you have a chance to put it to grammarly?

**Comment by wenjdu** [comment]
Yes I did, @maciejburda but not pro version of grammarly. haha

**Pull request merged**
